/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HrRouteImport } from './routes/hr'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers.index'
import { Route as SalesIndexRouteImport } from './routes/sales.index'
import { Route as PurchasesIndexRouteImport } from './routes/purchases.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as HrIndexRouteImport } from './routes/hr.index'
import { Route as DeliveriesIndexRouteImport } from './routes/deliveries.index'
import { Route as CylindersIndexRouteImport } from './routes/cylinders.index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as SuppliersNewRouteImport } from './routes/suppliers.new'
import { Route as SuppliersIdRouteImport } from './routes/suppliers.$id'
import { Route as SalesQuotationRouteImport } from './routes/sales.quotation'
import { Route as SalesNewRouteImport } from './routes/sales.new'
import { Route as SalesIdRouteImport } from './routes/sales.$id'
import { Route as PurchasesNewRouteImport } from './routes/purchases.new'
import { Route as PurchasesIdRouteImport } from './routes/purchases.$id'
import { Route as ProductsNewRouteImport } from './routes/products.new'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as HrEmployeesRouteImport } from './routes/hr.employees'
import { Route as HrIdRouteImport } from './routes/hr.$id'
import { Route as DeliveriesNewRouteImport } from './routes/deliveries.new'
import { Route as DeliveriesIdRouteImport } from './routes/deliveries.$id'
import { Route as CylindersNewRouteImport } from './routes/cylinders.new'
import { Route as CylindersIdRouteImport } from './routes/cylinders.$id'
import { Route as CustomersNewRouteImport } from './routes/customers.new'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as SuppliersIdStatementRouteImport } from './routes/suppliers.$id.statement'
import { Route as SuppliersIdEditRouteImport } from './routes/suppliers.$id.edit'
import { Route as SalesIdEditRouteImport } from './routes/sales.$id.edit'
import { Route as PurchasesIdEditRouteImport } from './routes/purchases.$id.edit'
import { Route as ProductsIdEditRouteImport } from './routes/products.$id.edit'
import { Route as HrIdStatementRouteImport } from './routes/hr.$id.statement'
import { Route as DeliveriesIdEditRouteImport } from './routes/deliveries.$id.edit'
import { Route as CylindersIdEditRouteImport } from './routes/cylinders.$id.edit'
import { Route as CustomersIdStatementRouteImport } from './routes/customers.$id.statement'
import { Route as CustomersIdEditRouteImport } from './routes/customers.$id.edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesIndexRoute = PurchasesIndexRouteImport.update({
  id: '/purchases/',
  path: '/purchases/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const HrIndexRoute = HrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HrRoute,
} as any)
const DeliveriesIndexRoute = DeliveriesIndexRouteImport.update({
  id: '/deliveries/',
  path: '/deliveries/',
  getParentRoute: () => rootRouteImport,
} as any)
const CylindersIndexRoute = CylindersIndexRouteImport.update({
  id: '/cylinders/',
  path: '/cylinders/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersNewRoute = SuppliersNewRouteImport.update({
  id: '/suppliers/new',
  path: '/suppliers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIdRoute = SuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesQuotationRoute = SalesQuotationRouteImport.update({
  id: '/sales/quotation',
  path: '/sales/quotation',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesNewRoute = SalesNewRouteImport.update({
  id: '/sales/new',
  path: '/sales/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIdRoute = SalesIdRouteImport.update({
  id: '/sales/$id',
  path: '/sales/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesNewRoute = PurchasesNewRouteImport.update({
  id: '/purchases/new',
  path: '/purchases/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesIdRoute = PurchasesIdRouteImport.update({
  id: '/purchases/$id',
  path: '/purchases/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HrEmployeesRoute = HrEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => HrRoute,
} as any)
const HrIdRoute = HrIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HrRoute,
} as any)
const DeliveriesNewRoute = DeliveriesNewRouteImport.update({
  id: '/deliveries/new',
  path: '/deliveries/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesIdRoute = DeliveriesIdRouteImport.update({
  id: '/deliveries/$id',
  path: '/deliveries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CylindersNewRoute = CylindersNewRouteImport.update({
  id: '/cylinders/new',
  path: '/cylinders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CylindersIdRoute = CylindersIdRouteImport.update({
  id: '/cylinders/$id',
  path: '/cylinders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIdStatementRoute = SuppliersIdStatementRouteImport.update({
  id: '/statement',
  path: '/statement',
  getParentRoute: () => SuppliersIdRoute,
} as any)
const SuppliersIdEditRoute = SuppliersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SuppliersIdRoute,
} as any)
const SalesIdEditRoute = SalesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SalesIdRoute,
} as any)
const PurchasesIdEditRoute = PurchasesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PurchasesIdRoute,
} as any)
const ProductsIdEditRoute = ProductsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProductsIdRoute,
} as any)
const HrIdStatementRoute = HrIdStatementRouteImport.update({
  id: '/statement',
  path: '/statement',
  getParentRoute: () => HrIdRoute,
} as any)
const DeliveriesIdEditRoute = DeliveriesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DeliveriesIdRoute,
} as any)
const CylindersIdEditRoute = CylindersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CylindersIdRoute,
} as any)
const CustomersIdStatementRoute = CustomersIdStatementRouteImport.update({
  id: '/statement',
  path: '/statement',
  getParentRoute: () => CustomersIdRoute,
} as any)
const CustomersIdEditRoute = CustomersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CustomersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/expenses': typeof ExpensesRoute
  '/hr': typeof HrRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/customers/new': typeof CustomersNewRoute
  '/cylinders/$id': typeof CylindersIdRouteWithChildren
  '/cylinders/new': typeof CylindersNewRoute
  '/deliveries/$id': typeof DeliveriesIdRouteWithChildren
  '/deliveries/new': typeof DeliveriesNewRoute
  '/hr/$id': typeof HrIdRouteWithChildren
  '/hr/employees': typeof HrEmployeesRoute
  '/products/$id': typeof ProductsIdRouteWithChildren
  '/products/new': typeof ProductsNewRoute
  '/purchases/$id': typeof PurchasesIdRouteWithChildren
  '/purchases/new': typeof PurchasesNewRoute
  '/sales/$id': typeof SalesIdRouteWithChildren
  '/sales/new': typeof SalesNewRoute
  '/sales/quotation': typeof SalesQuotationRoute
  '/suppliers/$id': typeof SuppliersIdRouteWithChildren
  '/suppliers/new': typeof SuppliersNewRoute
  '/customers/': typeof CustomersIndexRoute
  '/cylinders/': typeof CylindersIndexRoute
  '/deliveries/': typeof DeliveriesIndexRoute
  '/hr/': typeof HrIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/purchases/': typeof PurchasesIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/customers/$id/statement': typeof CustomersIdStatementRoute
  '/cylinders/$id/edit': typeof CylindersIdEditRoute
  '/deliveries/$id/edit': typeof DeliveriesIdEditRoute
  '/hr/$id/statement': typeof HrIdStatementRoute
  '/products/$id/edit': typeof ProductsIdEditRoute
  '/purchases/$id/edit': typeof PurchasesIdEditRoute
  '/sales/$id/edit': typeof SalesIdEditRoute
  '/suppliers/$id/edit': typeof SuppliersIdEditRoute
  '/suppliers/$id/statement': typeof SuppliersIdStatementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/customers/new': typeof CustomersNewRoute
  '/cylinders/$id': typeof CylindersIdRouteWithChildren
  '/cylinders/new': typeof CylindersNewRoute
  '/deliveries/$id': typeof DeliveriesIdRouteWithChildren
  '/deliveries/new': typeof DeliveriesNewRoute
  '/hr/$id': typeof HrIdRouteWithChildren
  '/hr/employees': typeof HrEmployeesRoute
  '/products/$id': typeof ProductsIdRouteWithChildren
  '/products/new': typeof ProductsNewRoute
  '/purchases/$id': typeof PurchasesIdRouteWithChildren
  '/purchases/new': typeof PurchasesNewRoute
  '/sales/$id': typeof SalesIdRouteWithChildren
  '/sales/new': typeof SalesNewRoute
  '/sales/quotation': typeof SalesQuotationRoute
  '/suppliers/$id': typeof SuppliersIdRouteWithChildren
  '/suppliers/new': typeof SuppliersNewRoute
  '/customers': typeof CustomersIndexRoute
  '/cylinders': typeof CylindersIndexRoute
  '/deliveries': typeof DeliveriesIndexRoute
  '/hr': typeof HrIndexRoute
  '/products': typeof ProductsIndexRoute
  '/purchases': typeof PurchasesIndexRoute
  '/sales': typeof SalesIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/customers/$id/statement': typeof CustomersIdStatementRoute
  '/cylinders/$id/edit': typeof CylindersIdEditRoute
  '/deliveries/$id/edit': typeof DeliveriesIdEditRoute
  '/hr/$id/statement': typeof HrIdStatementRoute
  '/products/$id/edit': typeof ProductsIdEditRoute
  '/purchases/$id/edit': typeof PurchasesIdEditRoute
  '/sales/$id/edit': typeof SalesIdEditRoute
  '/suppliers/$id/edit': typeof SuppliersIdEditRoute
  '/suppliers/$id/statement': typeof SuppliersIdStatementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/expenses': typeof ExpensesRoute
  '/hr': typeof HrRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/customers/new': typeof CustomersNewRoute
  '/cylinders/$id': typeof CylindersIdRouteWithChildren
  '/cylinders/new': typeof CylindersNewRoute
  '/deliveries/$id': typeof DeliveriesIdRouteWithChildren
  '/deliveries/new': typeof DeliveriesNewRoute
  '/hr/$id': typeof HrIdRouteWithChildren
  '/hr/employees': typeof HrEmployeesRoute
  '/products/$id': typeof ProductsIdRouteWithChildren
  '/products/new': typeof ProductsNewRoute
  '/purchases/$id': typeof PurchasesIdRouteWithChildren
  '/purchases/new': typeof PurchasesNewRoute
  '/sales/$id': typeof SalesIdRouteWithChildren
  '/sales/new': typeof SalesNewRoute
  '/sales/quotation': typeof SalesQuotationRoute
  '/suppliers/$id': typeof SuppliersIdRouteWithChildren
  '/suppliers/new': typeof SuppliersNewRoute
  '/customers/': typeof CustomersIndexRoute
  '/cylinders/': typeof CylindersIndexRoute
  '/deliveries/': typeof DeliveriesIndexRoute
  '/hr/': typeof HrIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/purchases/': typeof PurchasesIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/customers/$id/statement': typeof CustomersIdStatementRoute
  '/cylinders/$id/edit': typeof CylindersIdEditRoute
  '/deliveries/$id/edit': typeof DeliveriesIdEditRoute
  '/hr/$id/statement': typeof HrIdStatementRoute
  '/products/$id/edit': typeof ProductsIdEditRoute
  '/purchases/$id/edit': typeof PurchasesIdEditRoute
  '/sales/$id/edit': typeof SalesIdEditRoute
  '/suppliers/$id/edit': typeof SuppliersIdEditRoute
  '/suppliers/$id/statement': typeof SuppliersIdStatementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting'
    | '/expenses'
    | '/hr'
    | '/inventory'
    | '/login'
    | '/reports'
    | '/settings'
    | '/customers/$id'
    | '/customers/new'
    | '/cylinders/$id'
    | '/cylinders/new'
    | '/deliveries/$id'
    | '/deliveries/new'
    | '/hr/$id'
    | '/hr/employees'
    | '/products/$id'
    | '/products/new'
    | '/purchases/$id'
    | '/purchases/new'
    | '/sales/$id'
    | '/sales/new'
    | '/sales/quotation'
    | '/suppliers/$id'
    | '/suppliers/new'
    | '/customers/'
    | '/cylinders/'
    | '/deliveries/'
    | '/hr/'
    | '/products/'
    | '/purchases/'
    | '/sales/'
    | '/suppliers/'
    | '/customers/$id/edit'
    | '/customers/$id/statement'
    | '/cylinders/$id/edit'
    | '/deliveries/$id/edit'
    | '/hr/$id/statement'
    | '/products/$id/edit'
    | '/purchases/$id/edit'
    | '/sales/$id/edit'
    | '/suppliers/$id/edit'
    | '/suppliers/$id/statement'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting'
    | '/expenses'
    | '/inventory'
    | '/login'
    | '/reports'
    | '/settings'
    | '/customers/$id'
    | '/customers/new'
    | '/cylinders/$id'
    | '/cylinders/new'
    | '/deliveries/$id'
    | '/deliveries/new'
    | '/hr/$id'
    | '/hr/employees'
    | '/products/$id'
    | '/products/new'
    | '/purchases/$id'
    | '/purchases/new'
    | '/sales/$id'
    | '/sales/new'
    | '/sales/quotation'
    | '/suppliers/$id'
    | '/suppliers/new'
    | '/customers'
    | '/cylinders'
    | '/deliveries'
    | '/hr'
    | '/products'
    | '/purchases'
    | '/sales'
    | '/suppliers'
    | '/customers/$id/edit'
    | '/customers/$id/statement'
    | '/cylinders/$id/edit'
    | '/deliveries/$id/edit'
    | '/hr/$id/statement'
    | '/products/$id/edit'
    | '/purchases/$id/edit'
    | '/sales/$id/edit'
    | '/suppliers/$id/edit'
    | '/suppliers/$id/statement'
  id:
    | '__root__'
    | '/'
    | '/accounting'
    | '/expenses'
    | '/hr'
    | '/inventory'
    | '/login'
    | '/reports'
    | '/settings'
    | '/customers/$id'
    | '/customers/new'
    | '/cylinders/$id'
    | '/cylinders/new'
    | '/deliveries/$id'
    | '/deliveries/new'
    | '/hr/$id'
    | '/hr/employees'
    | '/products/$id'
    | '/products/new'
    | '/purchases/$id'
    | '/purchases/new'
    | '/sales/$id'
    | '/sales/new'
    | '/sales/quotation'
    | '/suppliers/$id'
    | '/suppliers/new'
    | '/customers/'
    | '/cylinders/'
    | '/deliveries/'
    | '/hr/'
    | '/products/'
    | '/purchases/'
    | '/sales/'
    | '/suppliers/'
    | '/customers/$id/edit'
    | '/customers/$id/statement'
    | '/cylinders/$id/edit'
    | '/deliveries/$id/edit'
    | '/hr/$id/statement'
    | '/products/$id/edit'
    | '/purchases/$id/edit'
    | '/sales/$id/edit'
    | '/suppliers/$id/edit'
    | '/suppliers/$id/statement'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingRoute: typeof AccountingRoute
  ExpensesRoute: typeof ExpensesRoute
  HrRoute: typeof HrRouteWithChildren
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  CustomersIdRoute: typeof CustomersIdRouteWithChildren
  CustomersNewRoute: typeof CustomersNewRoute
  CylindersIdRoute: typeof CylindersIdRouteWithChildren
  CylindersNewRoute: typeof CylindersNewRoute
  DeliveriesIdRoute: typeof DeliveriesIdRouteWithChildren
  DeliveriesNewRoute: typeof DeliveriesNewRoute
  ProductsIdRoute: typeof ProductsIdRouteWithChildren
  ProductsNewRoute: typeof ProductsNewRoute
  PurchasesIdRoute: typeof PurchasesIdRouteWithChildren
  PurchasesNewRoute: typeof PurchasesNewRoute
  SalesIdRoute: typeof SalesIdRouteWithChildren
  SalesNewRoute: typeof SalesNewRoute
  SalesQuotationRoute: typeof SalesQuotationRoute
  SuppliersIdRoute: typeof SuppliersIdRouteWithChildren
  SuppliersNewRoute: typeof SuppliersNewRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  CylindersIndexRoute: typeof CylindersIndexRoute
  DeliveriesIndexRoute: typeof DeliveriesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  PurchasesIndexRoute: typeof PurchasesIndexRoute
  SalesIndexRoute: typeof SalesIndexRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/': {
      id: '/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof PurchasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/': {
      id: '/hr/'
      path: '/'
      fullPath: '/hr/'
      preLoaderRoute: typeof HrIndexRouteImport
      parentRoute: typeof HrRoute
    }
    '/deliveries/': {
      id: '/deliveries/'
      path: '/deliveries'
      fullPath: '/deliveries/'
      preLoaderRoute: typeof DeliveriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cylinders/': {
      id: '/cylinders/'
      path: '/cylinders'
      fullPath: '/cylinders/'
      preLoaderRoute: typeof CylindersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/new': {
      id: '/suppliers/new'
      path: '/suppliers/new'
      fullPath: '/suppliers/new'
      preLoaderRoute: typeof SuppliersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$id': {
      id: '/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof SuppliersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/quotation': {
      id: '/sales/quotation'
      path: '/sales/quotation'
      fullPath: '/sales/quotation'
      preLoaderRoute: typeof SalesQuotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/new': {
      id: '/sales/new'
      path: '/sales/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof SalesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/$id': {
      id: '/sales/$id'
      path: '/sales/$id'
      fullPath: '/sales/$id'
      preLoaderRoute: typeof SalesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/new': {
      id: '/purchases/new'
      path: '/purchases/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof PurchasesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/$id': {
      id: '/purchases/$id'
      path: '/purchases/$id'
      fullPath: '/purchases/$id'
      preLoaderRoute: typeof PurchasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/new': {
      id: '/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/employees': {
      id: '/hr/employees'
      path: '/employees'
      fullPath: '/hr/employees'
      preLoaderRoute: typeof HrEmployeesRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/$id': {
      id: '/hr/$id'
      path: '/$id'
      fullPath: '/hr/$id'
      preLoaderRoute: typeof HrIdRouteImport
      parentRoute: typeof HrRoute
    }
    '/deliveries/new': {
      id: '/deliveries/new'
      path: '/deliveries/new'
      fullPath: '/deliveries/new'
      preLoaderRoute: typeof DeliveriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries/$id': {
      id: '/deliveries/$id'
      path: '/deliveries/$id'
      fullPath: '/deliveries/$id'
      preLoaderRoute: typeof DeliveriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cylinders/new': {
      id: '/cylinders/new'
      path: '/cylinders/new'
      fullPath: '/cylinders/new'
      preLoaderRoute: typeof CylindersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cylinders/$id': {
      id: '/cylinders/$id'
      path: '/cylinders/$id'
      fullPath: '/cylinders/$id'
      preLoaderRoute: typeof CylindersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$id/statement': {
      id: '/suppliers/$id/statement'
      path: '/statement'
      fullPath: '/suppliers/$id/statement'
      preLoaderRoute: typeof SuppliersIdStatementRouteImport
      parentRoute: typeof SuppliersIdRoute
    }
    '/suppliers/$id/edit': {
      id: '/suppliers/$id/edit'
      path: '/edit'
      fullPath: '/suppliers/$id/edit'
      preLoaderRoute: typeof SuppliersIdEditRouteImport
      parentRoute: typeof SuppliersIdRoute
    }
    '/sales/$id/edit': {
      id: '/sales/$id/edit'
      path: '/edit'
      fullPath: '/sales/$id/edit'
      preLoaderRoute: typeof SalesIdEditRouteImport
      parentRoute: typeof SalesIdRoute
    }
    '/purchases/$id/edit': {
      id: '/purchases/$id/edit'
      path: '/edit'
      fullPath: '/purchases/$id/edit'
      preLoaderRoute: typeof PurchasesIdEditRouteImport
      parentRoute: typeof PurchasesIdRoute
    }
    '/products/$id/edit': {
      id: '/products/$id/edit'
      path: '/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof ProductsIdEditRouteImport
      parentRoute: typeof ProductsIdRoute
    }
    '/hr/$id/statement': {
      id: '/hr/$id/statement'
      path: '/statement'
      fullPath: '/hr/$id/statement'
      preLoaderRoute: typeof HrIdStatementRouteImport
      parentRoute: typeof HrIdRoute
    }
    '/deliveries/$id/edit': {
      id: '/deliveries/$id/edit'
      path: '/edit'
      fullPath: '/deliveries/$id/edit'
      preLoaderRoute: typeof DeliveriesIdEditRouteImport
      parentRoute: typeof DeliveriesIdRoute
    }
    '/cylinders/$id/edit': {
      id: '/cylinders/$id/edit'
      path: '/edit'
      fullPath: '/cylinders/$id/edit'
      preLoaderRoute: typeof CylindersIdEditRouteImport
      parentRoute: typeof CylindersIdRoute
    }
    '/customers/$id/statement': {
      id: '/customers/$id/statement'
      path: '/statement'
      fullPath: '/customers/$id/statement'
      preLoaderRoute: typeof CustomersIdStatementRouteImport
      parentRoute: typeof CustomersIdRoute
    }
    '/customers/$id/edit': {
      id: '/customers/$id/edit'
      path: '/edit'
      fullPath: '/customers/$id/edit'
      preLoaderRoute: typeof CustomersIdEditRouteImport
      parentRoute: typeof CustomersIdRoute
    }
  }
}

interface HrIdRouteChildren {
  HrIdStatementRoute: typeof HrIdStatementRoute
}

const HrIdRouteChildren: HrIdRouteChildren = {
  HrIdStatementRoute: HrIdStatementRoute,
}

const HrIdRouteWithChildren = HrIdRoute._addFileChildren(HrIdRouteChildren)

interface HrRouteChildren {
  HrIdRoute: typeof HrIdRouteWithChildren
  HrEmployeesRoute: typeof HrEmployeesRoute
  HrIndexRoute: typeof HrIndexRoute
}

const HrRouteChildren: HrRouteChildren = {
  HrIdRoute: HrIdRouteWithChildren,
  HrEmployeesRoute: HrEmployeesRoute,
  HrIndexRoute: HrIndexRoute,
}

const HrRouteWithChildren = HrRoute._addFileChildren(HrRouteChildren)

interface CustomersIdRouteChildren {
  CustomersIdEditRoute: typeof CustomersIdEditRoute
  CustomersIdStatementRoute: typeof CustomersIdStatementRoute
}

const CustomersIdRouteChildren: CustomersIdRouteChildren = {
  CustomersIdEditRoute: CustomersIdEditRoute,
  CustomersIdStatementRoute: CustomersIdStatementRoute,
}

const CustomersIdRouteWithChildren = CustomersIdRoute._addFileChildren(
  CustomersIdRouteChildren,
)

interface CylindersIdRouteChildren {
  CylindersIdEditRoute: typeof CylindersIdEditRoute
}

const CylindersIdRouteChildren: CylindersIdRouteChildren = {
  CylindersIdEditRoute: CylindersIdEditRoute,
}

const CylindersIdRouteWithChildren = CylindersIdRoute._addFileChildren(
  CylindersIdRouteChildren,
)

interface DeliveriesIdRouteChildren {
  DeliveriesIdEditRoute: typeof DeliveriesIdEditRoute
}

const DeliveriesIdRouteChildren: DeliveriesIdRouteChildren = {
  DeliveriesIdEditRoute: DeliveriesIdEditRoute,
}

const DeliveriesIdRouteWithChildren = DeliveriesIdRoute._addFileChildren(
  DeliveriesIdRouteChildren,
)

interface ProductsIdRouteChildren {
  ProductsIdEditRoute: typeof ProductsIdEditRoute
}

const ProductsIdRouteChildren: ProductsIdRouteChildren = {
  ProductsIdEditRoute: ProductsIdEditRoute,
}

const ProductsIdRouteWithChildren = ProductsIdRoute._addFileChildren(
  ProductsIdRouteChildren,
)

interface PurchasesIdRouteChildren {
  PurchasesIdEditRoute: typeof PurchasesIdEditRoute
}

const PurchasesIdRouteChildren: PurchasesIdRouteChildren = {
  PurchasesIdEditRoute: PurchasesIdEditRoute,
}

const PurchasesIdRouteWithChildren = PurchasesIdRoute._addFileChildren(
  PurchasesIdRouteChildren,
)

interface SalesIdRouteChildren {
  SalesIdEditRoute: typeof SalesIdEditRoute
}

const SalesIdRouteChildren: SalesIdRouteChildren = {
  SalesIdEditRoute: SalesIdEditRoute,
}

const SalesIdRouteWithChildren =
  SalesIdRoute._addFileChildren(SalesIdRouteChildren)

interface SuppliersIdRouteChildren {
  SuppliersIdEditRoute: typeof SuppliersIdEditRoute
  SuppliersIdStatementRoute: typeof SuppliersIdStatementRoute
}

const SuppliersIdRouteChildren: SuppliersIdRouteChildren = {
  SuppliersIdEditRoute: SuppliersIdEditRoute,
  SuppliersIdStatementRoute: SuppliersIdStatementRoute,
}

const SuppliersIdRouteWithChildren = SuppliersIdRoute._addFileChildren(
  SuppliersIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingRoute: AccountingRoute,
  ExpensesRoute: ExpensesRoute,
  HrRoute: HrRouteWithChildren,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  CustomersIdRoute: CustomersIdRouteWithChildren,
  CustomersNewRoute: CustomersNewRoute,
  CylindersIdRoute: CylindersIdRouteWithChildren,
  CylindersNewRoute: CylindersNewRoute,
  DeliveriesIdRoute: DeliveriesIdRouteWithChildren,
  DeliveriesNewRoute: DeliveriesNewRoute,
  ProductsIdRoute: ProductsIdRouteWithChildren,
  ProductsNewRoute: ProductsNewRoute,
  PurchasesIdRoute: PurchasesIdRouteWithChildren,
  PurchasesNewRoute: PurchasesNewRoute,
  SalesIdRoute: SalesIdRouteWithChildren,
  SalesNewRoute: SalesNewRoute,
  SalesQuotationRoute: SalesQuotationRoute,
  SuppliersIdRoute: SuppliersIdRouteWithChildren,
  SuppliersNewRoute: SuppliersNewRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  CylindersIndexRoute: CylindersIndexRoute,
  DeliveriesIndexRoute: DeliveriesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  PurchasesIndexRoute: PurchasesIndexRoute,
  SalesIndexRoute: SalesIndexRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
